sudo: false
language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: '12'
    - node_js: '10'
# https://github.com/greenkeeperio/greenkeeper-lockfile#npm
before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
- docker pull localstack/localstack:0.11.5
- docker run -d --name localstack -p 4569:4569 -e SERVICES=dynamodb --rm localstack/localstack:0.11.5
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install: npm install
services:
  - docker
